version: '3.8'

services:
  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    environment:
      - REDIS_URL=redis-stack-server:6379
    depends_on:
      - redis-stack-server
    restart: unless-stopped

volumes:
  redisinsight:
